# Generated by Django 2.2 on 2019-04-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190424_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-update', '-timestamp']},
        ),
    ]
